name: currencies_project
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3 # State management system
  bloc: ^8.1.2 # State management system
  dio: ^5.3.0 # Api calls
  get_it: ^7.6.0 # DI (Service Locator)
  equatable: ^2.0.5 # To make models comparable
  json_serializable: ^6.7.1 # DTO Serialization
  json_annotation: ^4.8.1 # DTO Serialization
  intl: ^0.18.1 # DateFormatter
  shared_preferences: ^2.2.0 # Store settings

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
